import stage1 from '../../data/results/stage1_flat.json' with { type: 'json' };
import stage2 from '../../data/results/stage2_ion.json' with { type: 'json' };
import stage3 from '../../data/results/stage3_sc.json' with { type: 'json' };
import stage4 from '../../data/results/stage4_comparison.json' with { type: 'json' };
import bankD3R1 from '../../data/banks/rep_d3_r1_L0.json' with { type: 'json' };
import bankD3R3 from '../../data/banks/rep_d3_r3_L0.json' with { type: 'json' };
import paramsIon from '../../params/ion.json' with { type: 'json' };
import paramsSc from '../../params/sc.json' with { type: 'json' };
import paramsCycle from '../../params/cycle.json' with { type: 'json' };
export { stage1, stage2, stage3, stage4, bankD3R1, bankD3R3, paramsIon, paramsSc, paramsCycle };
